connection_string: AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
database: testdb
AUTH0_DOMAIN: wibblewobble.uk.auth0.com
API_IDENTIFIER: https://wibblewobble.uk.auth0.com/api/v2/