name: Build and deploy
env:
  OUTPUT_FOLDER: client/dist
on:
  push:
    branches:
      - main
jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Build and test
        run: |
          cd ./client
          yarn
          yarn build-only
          yarn test
          yarn lint
      - name: Publish website output
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        run: python -m pip install pyyaml
      - name: Install project dependencies
        run: |
          cd ./server
          poetry install
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'server/secret_config.yaml'
          propertyPath: 'migration_user'
          value: ${{ secrets.PIPELINE_SQL_MIGRATION_USER }}
          commitChange: false      
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'server/secret_config.yaml'
          propertyPath: 'migration_user_password'
          value: ${{ secrets.PIPELINE_SQL_MIGRATION_USER_PASSWORD }}
          commitChange: false      
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'server/secret_config.yaml'
          propertyPath: 'migration_user_password_encoded'
          value: ${{ secrets.PIPELINE_SQL_MIGRATION_USER_PASSWORD_ENCODED }}
          commitChange: false      
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'server/secret_config.yaml'
          propertyPath: 'app_user'
          value: ${{ secrets.PIPELINE_SQL_APP_USER }}
          commitChange: false      
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'server/secret_config.yaml'
          propertyPath: 'app_user_password'
          value: ${{ secrets.PIPELINE_SQL_APP_USER_PASSWORD }}
          commitChange: false
      - name: Lint using Flake8
        run: |
          cd ./server
          poetry run flake8
      - name: Alter migration settings
        run: cd ./server && python alter_configs.py
      - name: Install SQL
        run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=${{ secrets.PIPELINE_SQL_MIGRATION_USER_PASSWORD }}" -e "MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS" -p 1433:1433 --memory="5g" -d "mcr.microsoft.com/mssql/server:2022-latest"
      - name: Run migration
        run: |
          cd ./server
          . .venv/bin/activate
          alembic upgrade head
      - name: Test with pytest
        run: |
          cd ./server
          poetry run pytest
  provision_azure:
    runs-on: ubuntu-latest
    needs: [build_client, build_server]
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Ensure resource group exists
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create -g ${{ secrets.RESOURCE_GROUP }} -l ${{ secrets.RESOURCE_GROUP_LOCATION }}
      - name: Create a static web app
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az staticwebapp create \
                --name ${{ secrets.STATIC_WEB_APP_NAME }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --location ${{ secrets.STATIC_WEB_APP_LOCATION }} \
                --sku free
  deploy_static_web_app:
    needs: [ provision_azure ]
    runs-on: ubuntu-latest
    name: Deploy SWA
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get SWA deployment token
        uses: azure/cli@v2
        id: swa-token
        with:
          inlineScript: |
            SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ secrets.STATIC_WEB_APP_NAME }} -o tsv --query properties.apiKey)
            echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
            echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV
      - name: Download website
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}
      - name: Deploy frontend
        id: build-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: ${{ env.OUTPUT_FOLDER }}
