name: Build and deploy
env:
  OUTPUT_FOLDER: client/vue/dist
on:
  push:
    branches:
      - main
jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Build and test
        run: |
          cd ./client/vue
          yarn
          yarn build-only
          yarn test:unit
          yarn lint
      - name: Publish website output
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install project dependencies
        run: |
          cd ./server
          poetry install
      - name: Lint using Flake8
        uses: py-actions/flake8@v2
        with:
          working_directory: "server"
      - name: Test with pytest
        run: |
          poetry run pytest
  provision_azure:
    runs-on: ubuntu-latest
    needs: [build_client, build_server]
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Ensure resource group exists
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create -g ${{ vars.RESOURCE_GROUP }} -l ${{ vars.RESOURCE_GROUP_LOCATION }}
      - name: Create a static web app
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az staticwebapp create \
                --name ${{ vars.STATIC_WEB_APP_NAME }} \
                --resource-group ${{ vars.RESOURCE_GROUP }} \
                --location ${{ vars.STATIC_WEB_APP_LOCATION }} \
                --sku free
  deploy_static_web_app:
    needs: [ provision_azure ]
    runs-on: ubuntu-latest
    name: Deploy SWA
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get SWA deployment token
        uses: azure/cli@v2
        id: swa-token
        with:
          inlineScript: |
            SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ vars.STATIC_WEB_APP_NAME }} -o tsv --query properties.apiKey)
            echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
            echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV
      - name: Download website
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}
      - name: Deploy frontend
        id: build-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: ${{ env.OUTPUT_FOLDER }}
