name: Provision Azure
env:
  CLIENT_OUTPUT_FOLDER: client/dist
  SERVER_OUTPUT_FOLDER: server
on: [ workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  provision_azure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Register subscription for for Domain Registration
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: az provider register --namespace Microsoft.DomainRegistration
      - name: Create a resource group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create -g ${{ secrets.RESOURCE_GROUP }} -l ${{ secrets.RESOURCE_GROUP_LOCATION }}
      - name: Create a static web app 
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az staticwebapp create \
                --name ${{ secrets.STATIC_WEB_APP_NAME }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --location ${{ secrets.STATIC_WEB_APP_LOCATION }} \
                --sku free
      - name: Create Cosmos DB
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az cosmosdb create \
                --name ${{ secrets.COSMOS_NAME }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --kind GlobalDocumentDB \
                --enable-free-tier true            
            az cosmosdb sql database create \
                --account-name ${{ secrets.COSMOS_NAME }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --name ${{ secrets.COSMOS_DATABASE }}
            az cosmosdb sql container create \
                --account-name ${{ secrets.COSMOS_NAME }} \
                --database-name ${{ secrets.COSMOS_DATABASE }} \
                --name ${{ secrets.COSMOS_CONTAINER }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --partition-key-path ${{ secrets.COSMOS_PARTITION_KEY_PATH }}
